name: Python Build and Upload to S3

on:
  push:
    branches:
      - main
    #paths:
      #- Script/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Test Python Code
      #run: |
        #python -m pytest Script/GameScript.py
    
    - name: Install Wine and Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine32 winbind
        sudo apt install -y python3-pip
        sudo apt install -y python-is-python3
        sudo apt install -y wget
  
    - name: Set up Wine
      run: |
        mkdir -p $HOME/wine32
        WINEARCH=win32 WINEPREFIX=$HOME/wine32 wine wineboot
  
    - name: Download and Install Python in Wine
      run: |
        wget https://www.python.org/ftp/python/3.9.0/python-3.9.0.exe -O python-installer.exe
        WINEPREFIX=$HOME/wine32 wine python-installer.exe /quiet InstallAllUsers=1 PrependPath=1
  
    - name: Install PyInstaller in Wine
      run: |
        WINEPREFIX=$HOME/wine32 wine pip install pyinstaller
        
    - name: Convert Python Script to EXE
      run: |
        WINEPREFIX=$HOME/wine32 wine pyinstaller --onefile Client_TCP_sample.py
        mkdir -p BinaryScript
        mv dist/Client_TCP_sample.exe BinaryScript/
    
    - name: Compress folder
      run: |
        zip -r BinaryScript.zip BinaryScript
        mkdir UPLOAD
        mv Script.zip ./UPLOAD

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Deploy to S3
      run: aws s3 sync UPLOAD s3://projecttol-s3/ProjectTOL_Script --delete --request-payer requester
