name: Python Build and Upload to S3

on:
  push:
    branches:
      - main
    #paths:
      #- Script/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Test Python Code
      #run: |
        #python -m pytest Script/GameScript.py

    - name: Convert to Binary with PyInstaller
      run: |
        pyinstaller --onefile Script/Client_TCP_sample.py
  
    - name: Compress folder
      run: |
        zip -r BinaryScript.zip dist
        mkdir UPLOAD
        mv BinaryScript.zip ./UPLOAD
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Deploy to S3
      run: aws s3 sync UPLOAD s3://projecttol-s3/ProjectTOL_Script --delete --request-payer requester
