name: Python Build and Upload to S3

on:
  push:
    branches:
      - main
    #paths:
      #- Script/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #- name: Test Python Code
      #run: |
        #python -m pytest Script/GameScript.py
    
    - name: Install Wine and PyInstaller
      run: |
        sudo dpkg --add-architecture amd64
        sudo apt update
        sudo apt install -y wine64
        pip install pyinstaller
  
    - name: Set up Wine
      run: |
        mkdir wine64
        cd wine64
        WINEARCH=win64 WINEPREFIX=/wine64 wine64 wineboot
    
    - name: Convert Python Script to EXE
      run: |
        WINEARCH=win64 WINEPREFIX=/wine64 wine64 pyinstaller --onefile Client_TCP_sample.py
        mkdir -p BinaryScript
        mv dist/hello.exe BinaryScript/
    
    - name: Compress folder
      run: |
        zip -r BinaryScript.zip BinaryScript
        mkdir UPLOAD
        mv Script.zip ./UPLOAD

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Deploy to S3
      run: aws s3 sync UPLOAD s3://projecttol-s3/ProjectTOL_Script --delete --request-payer requester
